import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function getDistance(lat1: number, lon1: number, lat2: number, lon2: number) {
  const R = 6371;
  const dLat = (lat2 - lat1) * (Math.PI / 180);
  const dLon = (lon2 - lon1) * (Math.PI / 180);
  const a = 
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos(lat1 * (Math.PI / 180)) * Math.cos(lat2 * (Math.PI / 180)) * 
    Math.sin(dLon / 2) * Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c;
}

export const DEFAULT_IMAGE = "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&q=80&w=800";

export const ISTANBUL_DATA = {
  "sehir": "İstanbul",
  "toplam_mekan_sayisi": 101,
  "toplam_otel_sayisi": 40,
  "turistik_mekanlar": [
    { "isim": "Ayasofya", "isim_en": "Hagia Sophia Grand Mosque", "tur": "Cami / Tarihi Yapı", "tur_en": "Mosque / Historical Building", "kisa_tarihce": "537'de katedral olarak açılan yapı, Fatih'in fethiyle camiye dönüşmüş dünya mirasıdır.", "kisa_tarihce_en": "Opened as a cathedral in 537, it was converted into a mosque with Fatih's conquest and is a world heritage site.", "koordinat": { "enlem": 41.0086, "boylam": 28.9799 }, "gorsel": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Hagia_Sophia_%28228968325%29.jpeg/960px-Hagia_Sophia_%28228968325%29.jpeg" },
    { "isim": "Sultanahmet Camii", "isim_en": "Blue Mosque", "tur": "Cami", "tur_en": "Mosque", "kisa_tarihce": "17. yüzyılda Mavi Camii olarak da bilinen, 6 minareli mimari şaheser.", "kisa_tarihce_en": "A 17th-century architectural masterpiece also known as the Blue Mosque, famous for its 6 minarets.", "koordinat": { "enlem": 41.0054, "boylam": 28.9768 }, "gorsel": "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&q=80&w=800" },
    { "isim": "Topkapı Sarayı Müzesi", "isim_en": "Topkapi Palace Museum", "tur": "Saray / Müze", "tur_en": "Palace / Museum", "kisa_tarihce": "Osmanlı padişahlarının 400 yıl boyunca ikamet ettiği idari merkez.", "kisa_tarihce_en": "The administrative center where Ottoman Sultans resided for 400 years.", "koordinat": { "enlem": 41.0115, "boylam": 28.9833 }, "gorsel": "https://images.unsplash.com/photo-1566371534003-685cc1c59cfc?auto=format&fit=crop&q=80&w=800" },
    { "isim": "Dolmabahçe Sarayı", "isim_en": "Dolmabahce Palace", "tur": "Saray / Müze", "tur_en": "Palace / Museum", "kisa_tarihce": "19. yüzyılda inşa edilen, Batı mimarili görkemli Osmanlı sahil sarayı.", "kisa_tarihce_en": "A magnificent 19th-century Ottoman waterfront palace built in Western architecture.", "koordinat": { "enlem": 41.0392, "boylam": 29.0020 }, "gorsel": "https://images.unsplash.com/photo-1590604109724-40660f545195?auto=format&fit=crop&q=80&w=800" },
    { "isim": "Galata Kulesi", "isim_en": "Galata Tower", "tur": "Kule / Manzara", "tur_en": "Tower / View", "kisa_tarihce": "1348'de Cenevizliler tarafından inşa edilen ikonik kule.", "kisa_tarihce_en": "An iconic tower built by the Genoese in 1348.", "koordinat": { "enlem": 41.0256, "boylam": 28.9741 }, "gorsel": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Istanbul_asv2020-02_img48_Galata_Tower.jpg/960px-Istanbul_asv2020-02_img48_Galata_Tower.jpg" },
    { "isim": "Kız Kulesi", "isim_en": "Maiden's Tower", "tur": "Tarihi Yapı / Manzara", "tur_en": "Historical Building / View", "kisa_tarihce": "Boğaz'ın girişinde, antik çağlardan beri var olan efsanevi yapı.", "kisa_tarihce_en": "A legendary structure at the entrance of the Bosphorus that has existed since ancient times.", "koordinat": { "enlem": 41.0211, "boylam": 29.0041 }, "gorsel": "https://images.unsplash.com/photo-1614742617631-098520894567?auto=format&fit=crop&q=80&w=800" },
    { "isim": "Yerebatan Sarnıcı", "isim_en": "Basilica Cistern", "tur": "Sarnıç / Müze", "tur_en": "Cistern / Museum", "kisa_tarihce": "6. yüzyılda inşa edilen, Medusa başlarıyla ünlü dev yeraltı su deposu.", "kisa_tarihce_en": "A giant 6th-century underground water reservoir famous for its Medusa heads.", "koordinat": { "enlem": 41.0084, "boylam": 28.9779 }, "gorsel": "https://images.unsplash.com/photo-1590604109724-40660f545195?auto=format&fit=crop&q=80&w=800" },
    { "isim": "Süleymaniye Camii", "isim_en": "Suleymaniye Mosque", "tur": "Cami", "tur_en": "Mosque", "kisa_tarihce": "Mimar Sinan'ın Kanuni Sultan Süleyman için yaptığı kalfalık eseri.", "kisa_tarihce_en": "The journeyman work of Mimar Sinan, built for Suleiman the Magnificent.", "koordinat": { "enlem": 41.0161, "boylam": 28.9639 }, "gorsel": "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&q=80&w=800" },
    { "isim": "Kapalıçarşı", "isim_en": "Grand Bazaar", "tur": "Tarihi Çarşı", "tur_en": "Historical Bazaar", "kisa_tarihce": "4000'den fazla dükkanıyla dünyanın en eski ticaret merkezlerinden biri.", "kisa_tarihce_en": "One of the world's oldest shopping centers with more than 4,000 shops.", "koordinat": { "enlem": 41.0107, "boylam": 28.9681 }, "gorsel": "https://images.unsplash.com/photo-1566371534003-685cc1c59cfc?auto=format&fit=crop&q=80&w=800" },
    { "isim": "Mısır Çarşısı", "isim_en": "Spice Bazaar", "tur": "Tarihi Çarşı", "tur_en": "Historical Bazaar", "kisa_tarihce": "1660'tan beri baharat ve yöresel lezzetlerin merkezi olan tarihi çarşı.", "kisa_tarihce_en": "A historical bazaar that has been the center of spices and local delicacies since 1660.", "koordinat": { "enlem": 41.0164, "boylam": 28.9706 }, "gorsel": "https://images.unsplash.com/photo-1590604109724-40660f545195?auto=format&fit=crop&q=80&w=800" },
    { "isim": "Pierre Loti Tepesi", "isim_en": "Pierre Loti Hill", "tur": "Manzara / Kafe", "tur_en": "View / Cafe", "kisa_tarihce": "Haliç manzarasına hakim, adını Fransız yazardan alan popüler tepe.", "kisa_tarihce_en": "Popular hill named after the French writer, offering a panoramic view of the Golden Horn.", "koordinat": { "enlem": 41.0535, "boylam": 28.9338 }, "gorsel": "https://images.unsplash.com/photo-1614742617631-098520894567?auto=format&fit=crop&q=80&w=800" },
    { "isim": "Rumeli Hisarı", "isim_en": "Rumeli Fortress", "tur": "Kale / Müze", "tur_en": "Fortress / Museum", "kisa_tarihce": "Fatih Sultan Mehmed tarafından İstanbul'un fethi öncesi 4 ayda yapılmıştır.", "kisa_tarihce_en": "Built by Sultan Mehmed the Conqueror in just 4 months prior to the conquest of Istanbul.", "koordinat": { "enlem": 41.0851, "boylam": 29.0566 }, "gorsel": "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&q=80&w=800" },
    { "isim": "İstanbul Arkeoloji Müzeleri", "isim_en": "Istanbul Archaeology Museums", "tur": "Müze", "tur_en": "Museum", "kisa_tarihce": "İskender Lahdi gibi dünya çapında eserlerin sergilendiği ilk Türk müzesi.", "kisa_tarihce_en": "The first Turkish museum where world-class artifacts like the Alexander Sarcophagus are exhibited.", "koordinat": { "enlem": 41.0116, "boylam": 28.9813 }, "gorsel": "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&q=80&w=800" },
    { "isim": "Beylerbeyi Sarayı", "isim_en": "Beylerbeyi Palace", "tur": "Saray / Müze", "tur_en": "Palace / Museum", "kisa_tarihce": "Osmanlı padişahlarının yazlık konutu olarak Boğaz kıyısına yapılmıştır.", "kisa_tarihce_en": "Built on the banks of the Bosphorus as a summer residence for Ottoman Sultans.", "koordinat": { "enlem": 41.0427, "boylam": 29.0401 }, "gorsel": "https://images.unsplash.com/photo-1590604109724-40660f545195?auto=format&fit=crop&q=80&w=800" },
    { "isim": "Ortaköy Camii", "isim_en": "Ortakoy Mosque", "tur": "Cami / Manzara", "tur_en": "Mosque / View", "kisa_tarihce": "Boğaz Köprüsü eşliğinde İstanbul'un en çok fotoğraflanan barok yapısı.", "kisa_tarihce_en": "The most photographed Baroque building in Istanbul, with the Bosphorus Bridge in the background.", "koordinat": { "enlem": 41.0473, "boylam": 29.0269 }, "gorsel": "https://images.unsplash.com/photo-1614742617631-098520894567?auto=format&fit=crop&q=80&w=800" },
    { "isim": "Gülhane Parkı", "isim_en": "Gulhane Park", "tur": "Tarihi Park", "tur_en": "Historical Park", "kisa_tarihce": "Sarayın eski dış bahçesi, tarihte Tanzimat Fermanı'na ev sahipliği yapmıştır.", "kisa_tarihce_en": "The former outer garden of the palace, historical site where the Tanzimat Edict was proclaimed.", "koordinat": { "enlem": 41.0128, "boylam": 28.9815 }, "gorsel": "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&q=80&w=800" },
    { "isim": "Taksim Meydanı", "isim_en": "Taksim Square", "tur": "Meydan / Şehir Merkezi", "tur_en": "Square / City Center", "kisa_tarihce": "Cumhuriyet Anıtı'na ev sahipliği yapan, modern İstanbul'un kalbi sayılan meydan.", "kisa_tarihce_en": "Considered the heart of modern Istanbul, home to the Republic Monument.", "koordinat": { "enlem": 41.0369, "boylam": 28.9851 }, "gorsel": "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&q=80&w=800" },
    { "isim": "İstiklal Caddesi", "isim_en": "Istiklal Avenue", "tur": "Tarihi Cadde / Alışveriş", "tur_en": "Historical Avenue / Shopping", "kisa_tarihce": "Beyoğlu'nun tarihi dokusu, tramvayı ve pasajlarıyla ünlü yaya yolu.", "kisa_tarihce_en": "A famous pedestrian street in Beyoğlu known for its historical architecture, tram, and passages.", "koordinat": { "enlem": 41.0341, "boylam": 28.9791 }, "gorsel": "https://images.unsplash.com/photo-1590604109724-40660f545195?auto=format&fit=crop&q=80&w=800" },
    { "isim": "Bağdat Caddesi", "isim_en": "Bagdat Avenue", "tur": "Alışveriş / Yaşam", "tur_en": "Shopping / Lifestyle", "kisa_tarihce": "Anadolu Yakası'nın en popüler, lüks mağaza ve cafelerle dolu uzun caddesi.", "kisa_tarihce_en": "The most popular avenue on the Asian side, filled with luxury shops and cafes.", "koordinat": { "enlem": 40.9632, "boylam": 29.0655 } },
    { "isim": "Belgrad Ormanı", "isim_en": "Belgrade Forest", "tur": "Doğa / Park", "tur_en": "Nature / Forest", "kisa_tarihce": "Osmanlı'dan beri şehrin su kaynaklarını koruyan en büyük yeşil alanı.", "kisa_tarihce_en": "The largest green area of the city, protecting water resources since the Ottoman era.", "koordinat": { "enlem": 41.1819, "boylam": 28.9565 } },
    { "isim": "Büyük Çamlıca Tepesi", "isim_en": "Camlica Hill", "tur": "Manzara / Park", "tur_en": "View / Park", "kisa_tarihce": "İstanbul'un en yüksek noktalarından biri, panoramik Boğaz manzarası sunar.", "kisa_tarihce_en": "One of the highest points in Istanbul, offering a panoramic view of the Bosphorus.", "koordinat": { "enlem": 41.0287, "boylam": 29.0667 } },
    { "isim": "Galata Köprüsü", "isim_en": "Galata Bridge", "tur": "Köprü / Tarihi Yapı", "tur_en": "Bridge / Historical Structure", "kisa_tarihce": "Eminönü ve Karaköy'ü bağlayan, balıkçılarıyla ünlü sembolik köprü.", "kisa_tarihce_en": "A symbolic bridge connecting Eminönü and Karaköy, famous for its fishermen.", "koordinat": { "enlem": 41.0202, "boylam": 28.9734 } },
    { "isim": "15 Temmuz Şehitler Köprüsü", "isim_en": "Bosphorus Bridge", "tur": "Köprü", "tur_en": "Bridge", "kisa_tarihce": "Asya ve Avrupa'yı ilk kez birbirine bağlayan, 1973 yapımı Boğaz köprüsü.", "kisa_tarihce_en": "The first bridge connecting Asia and Europe, built in 1973.", "koordinat": { "enlem": 41.0458, "boylam": 29.0345 } },
    { "isim": "Kadıköy Boğa Heykeli", "isim_en": "Kadikoy Bull Statue", "tur": "Meydan / Yaşam / Heykel", "tur_en": "Square / Lifestyle / Statue", "kisa_tarihce": "1864 yapımı orijinal heykel, Kadıköy'ün en popüler simgesidir.", "kisa_tarihce_en": "The original statue made in 1864, Kadıköy's most popular symbol.", "koordinat": { "enlem": 40.9904, "boylam": 29.0305 } },
    { "isim": "Moda Sahili", "isim_en": "Moda Coast", "tur": "Sahil / Manzara", "tur_en": "Coastline / View", "kisa_tarihce": "Cumhuriyet sonrası İstanbul burjuvazisinin ve günümüz gençliğinin uğrak yeri.", "kisa_tarihce_en": "A popular spot for Istanbul youth and the bourgeoisie after the Republic.", "koordinat": { "enlem": 40.9791, "boylam": 29.0239 }, "gorsel": "https://idsb.tmgrup.com.tr/ly/uploads/images/2021/12/17/168062.jpg" },
    { "isim": "Bebek Sahili", "isim_en": "Bebek Coast", "tur": "Sahil / Sosyalleşme", "tur_en": "Coastline / Socializing", "kisa_tarihce": "Boğaz hattının en lüks semti ve yürüyüş parkuruyla ünlü sahil şeridi.", "kisa_tarihce_en": "The most luxurious neighborhood on the Bosphorus line, famous for its walking trail.", "koordinat": { "enlem": 41.0762, "boylam": 29.0435 }, "gorsel": "https://s2.dmcdn.net/v/SIZ_11VYEk4ZpD5D3/x1080" },
    { "isim": "Kuzguncuk", "isim_en": "Kuzguncuk", "tur": "Tarihi Semt", "tur_en": "Historical District", "kisa_tarihce": "Ahşap evleri ve hoşgörü kültürüyle bilinen, dizilerin platosu tarihi mahalle.", "kisa_tarihce_en": "A historic neighborhood known for its wooden houses and culture of tolerance, often used as a film set.", "koordinat": { "enlem": 41.0366, "boylam": 29.0306 } },
    { "isim": "Atatürk Arboretumu", "isim_en": "Ataturk Arboretum", "tur": "Doğa / Botanik Bahçe", "tur_en": "Nature / Botanical Garden", "kisa_tarihce": "Binlerce bitki türüne ev sahipliği yapan canlı bir ağaç müzesidir.", "kisa_tarihce_en": "A living tree museum home to thousands of plant species.", "koordinat": { "enlem": 41.1764, "boylam": 28.9859 } },
    { "isim": "Zorlu Center", "isim_en": "Zorlu Center", "tur": "Modern Yaşam / AVM", "tur_en": "Modern Life / Shopping Mall", "kisa_tarihce": "Lüks markaları ve performans sanatları merkeziyle modern İstanbul'un yüzü.", "kisa_tarihce_en": "The face of modern Istanbul with its luxury brands and performing arts center.", "koordinat": { "enlem": 41.0665, "boylam": 29.0169 }, "gorsel": "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&q=80&w=800" },
    { "isim": "Haydarpaşa Garı", "isim_en": "Haydarpasa Terminal", "tur": "Tarihi Yapı / İstasyon", "tur_en": "Historical Structure / Station", "kisa_tarihce": "1908'de Alman mimarlarca yapılan, Hicaz Demiryolu'nun başlangıç noktası.", "kisa_tarihce_en": "Built by German architects in 1908, the starting point of the Hejaz Railway.", "koordinat": { "enlem": 40.9968, "boylam": 29.0189 } },
    { "isim": "Sirkeci Garı", "isim_en": "Sirkeci Terminal", "tur": "Tarihi Yapı / İstasyon", "tur_en": "Historical Structure / Station", "kisa_tarihce": "Ünlü Şark Ekspresi'nin (Orient Express) son durağı olan tarihi gar.", "kisa_tarihce_en": "The historical terminal that was the last stop of the famous Orient Express.", "koordinat": { "enlem": 41.0152, "boylam": 28.9774 } },
    { "isim": "Maçka Demokrasi Parkı", "isim_en": "Macka Park", "tur": "Park / Dinlenme", "tur_en": "Park / Recreation", "kisa_tarihce": "Şehrin merkezinde teleferik hattına da ev sahipliği yapan popüler park.", "kisa_tarihce_en": "Popular park in the city center that also hosts a cable car line.", "koordinat": { "enlem": 41.0454, "boylam": 28.9926 }, "gorsel": "https://cdn.goturkiye.com/istanbul-v2/macka-park---istanbul.jpg" },
    { "isim": "Otağtepe Fatih Korusu", "isim_en": "Otagtepe Fatih Grove", "tur": "Manzara / Park", "tur_en": "View / Park", "kisa_tarihce": "İki köprüyü aynı anda gören, İstanbul'un en iyi fotoğraf noktasıdır.", "kisa_tarihce_en": "The best photo spot in Istanbul, with a view of two bridges simultaneously.", "koordinat": { "enlem": 41.0927, "boylam": 29.0889 }, "gorsel": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/7d/cf/3a/otagtepe-eski-adiyla.jpg?w=1200&h=-1&s=1" },
    { "isim": "İstinye Park", "isim_en": "Istinye Park", "tur": "Alışveriş Merkezi", "tur_en": "Shopping Mall", "kisa_tarihce": "Açık ve kapalı alan konseptiyle İstanbul'un en lüks AVM'lerinden biri.", "kisa_tarihce_en": "One of the most luxurious shopping malls in Istanbul with both open and closed area concepts.", "koordinat": { "enlem": 41.1124, "boylam": 29.0351 } },
    { "isim": "Balat Renkli Evler", "isim_en": "Colored Houses of Balat", "tur": "Tarihi Semt / Turizm", "tur_en": "Historical District / Tourism", "kisa_tarihce": "Haliç kıyısında yer alan, UNESCO korumasındaki tarihi ve renkli evler.", "kisa_tarihce_en": "UNESCO-protected historic and colorful houses located on the shores of the Golden Horn.", "koordinat": { "enlem": 41.0326, "boylam": 28.9475 }, "gorsel": "https://www.bizevdeyokuz.com/wp-content/uploads/balat-kapak.jpg" },
    { "isim": "Vialand (Isfanbul)", "isim_en": "Vialand Theme Park", "tur": "Tema Park", "tur_en": "Theme Park", "kisa_tarihce": "Türkiye'nin ilk ve en büyük tematik eğlence parkı ve yaşam merkezi.", "kisa_tarihce_en": "Turkey's first and largest thematic amusement park and lifestyle center.", "koordinat": { "enlem": 41.0772, "boylam": 28.9221 }, "gorsel": "https://trs3.cloudspark.com.tr/online/img/rides-pages/sato/s1.jpg?w=3840&q=100" },
    { "isim": "İstanbul Akvaryum (Florya)", "isim_en": "Istanbul Aquarium", "tur": "Eğlence / Akvaryum", "tur_en": "Entertainment / Aquarium", "kisa_tarihce": "Dünyanın en büyük tematik akvaryumlarından biridir.", "kisa_tarihce_en": "One of the largest thematic aquariums in the world.", "koordinat": { "enlem": 40.9639, "boylam": 28.7981 }, "gorsel": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2b/1c/ff/4d/the-longest-aquarium.jpg?w=1000&h=-1&s=1" },
    { "isim": "Sapphire Seyir Terası", "isim_en": "Sapphire Observation Deck", "tur": "Manzara / Modern Yapı", "tur_en": "View / Modern Structure", "kisa_tarihce": "236 metre yükseklikten şehri 360 derece izleme imkanı sunan gökdelen.", "kisa_tarihce_en": "Skyscraper offering a 360-degree view of the city from a height of 236 meters.", "koordinat": { "enlem": 41.0851, "boylam": 29.0069 } },
    { "isim": "Atatürk Kültür Merkezi", "isim_en": "Ataturk Cultural Center", "tur": "Sanat Merkezi", "tur_en": "Art Center", "kisa_tarihce": "Modern tasarımıyla Türkiye'nin sanat hafızası ve opera binası.", "kisa_tarihce_en": "Turkey's art memory and opera house with its modern design.", "koordinat": { "enlem": 41.0367, "boylam": 28.9869 } },
    { "isim": "Yıldız Parkı", "isim_en": "Yildiz Park", "tur": "Park / Doğa", "tur_en": "Park / Nature", "kisa_tarihce": "Beşiktaş'ta saray kompleksi içinde yer alan tarihi koru.", "kisa_tarihce_en": "Historical grove located within the palace complex in Beşiktaş.", "koordinat": { "enlem": 41.0489, "boylam": 29.0118 }, "gorsel": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Yildiz_Park_01.jpg/960px-Yildiz_Park_01.jpg" },
    { "isim": "Polonezköy Tabiat Parkı", "isim_en": "Polonezkoy Nature Park", "tur": "Doğa / Köy", "tur_en": "Nature / Village", "kisa_tarihce": "19. yüzyılda Polonyalı sürgünler tarafından kurulan yemyeşil yerleşim.", "kisa_tarihce_en": "A lush settlement founded by Polish exiles in the 19th century.", "koordinat": { "enlem": 41.1192, "boylam": 29.2131 } },
    { "isim": "Haliç Metro Köprüsü", "isim_en": "Golden Horn Metro Bridge", "tur": "Köprü / Seyir", "tur_en": "Bridge / Viewpoint", "kisa_tarihce": "Modern tasarımı ve üzerindeki metro durağı ile eşsiz bir manzara noktası.", "kisa_tarihce_en": "An unique viewpoint with its modern design and metro station on it.", "koordinat": { "enlem": 41.0236, "boylam": 28.9664 } },
    { "isim": "Caddebostan Sahili", "isim_en": "Caddebostan Coast", "tur": "Sahil / Etkinlik", "tur_en": "Coast / Activity", "kisa_tarihce": "Bisiklet yolları ve parklarıyla Anadolu Yakası'nın nefes alma noktası.", "kisa_tarihce_en": "The breathing point of the Anatolian Side with its bicycle paths and parks.", "koordinat": { "enlem": 40.9678, "boylam": 29.0569 }, "gorsel": "https://iasbh.tmgrup.com.tr/351d29/1200/675/0/176/1280/896?u=https://isbh.tmgrup.com.tr/sbh/2025/03/11/caddebostan-sahili-nerede-nasil-gidilir-caddebostan-sahile-hangi-metro-gider-ve-hangi-durakta-inilir-e1-1741697995356.jpg" },
    { "isim": "Nakkaştepe Millet Bahçesi", "isim_en": "Nakkastepe National Garden", "tur": "Manzara / Park", "tur_en": "View / Park", "kisa_tarihce": "Boğaz'a karşı zipline ve yürüyüş alanları sunan modern park.", "kisa_tarihce_en": "Modern park offering zipline and walking areas against the Bosphorus.", "koordinat": { "enlem": 41.0375, "boylam": 29.0378 } },
    { "isim": "Çiçek Pasajı", "isim_en": "Cicek Pasaji (Flower Passage)", "tur": "Tarihi Yapı / Eğlence", "tur_en": "Historical Building / Entertainment", "kisa_tarihce": "Beyoğlu'nun en süslü binası, eski adıyla Cité de Péra.", "kisa_tarihce_en": "The most ornate building in Beyoğlu, formerly known as Cité de Péra.", "koordinat": { "enlem": 41.0336, "boylam": 28.9774 } },
    { "isim": "Fransız Sokağı", "isim_en": "French Street", "tur": "Kültür / Eğlence", "tur_en": "Culture / Entertainment", "kisa_tarihce": "Beyoğlu'nda Paris atmosferini yansıtan renkli ve basamaklı sokak.", "kisa_tarihce_en": "A colorful and tiered street in Beyoğlu reflecting the Parisian atmosphere.", "koordinat": { "enlem": 41.0317, "boylam": 28.9798 } },
    { "isim": "Akaretler Sıraevler", "isim_en": "Akaretler Row Houses", "tur": "Tarihi Yapı / Mimari", "tur_en": "Historical Building / Architecture", "kisa_tarihce": "Sultan Abdülaziz döneminde saray çalışanları için yapılan ilk lojmanlar.", "kisa_tarihce_en": "The first public housing built for palace employees during the reign of Sultan Abdulaziz.", "koordinat": { "enlem": 41.0425, "boylam": 29.0001 }, "gorsel": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Akaretler%2C_Be%C5%9Fikta%C5%9F.JPG/960px-Akaretler%2C_Be%C5%9Fikta%C5%9F.JPG" },
    { "isim": "Arnavutköy Sahili", "isim_en": "Arnavutkoy Coast", "tur": "Sahil / Tarihi Semt", "tur_en": "Coast / Historical District", "kisa_tarihce": "Yalıları ve balık lokantalarıyla ünlü, mimarisi bozulmamış Boğaz köyü.", "kisa_tarihce_en": "A Bosphorus village with preserved architecture, famous for its mansions and fish restaurants.", "koordinat": { "enlem": 41.0673, "boylam": 29.0436 }, "gorsel": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Arnavutkoy-SA400006.jpg/960px-Arnavutkoy-SA400006.jpg" },
    { "isim": "Kanlıca", "isim_en": "Kanlica", "tur": "Tarihi Semt", "tur_en": "Historical District", "kisa_tarihce": "Meşhur yoğurdu ve sakin atmosferiyle bilinen tarihi semt.", "kisa_tarihce_en": "A historic neighborhood known for its famous yogurt and peaceful atmosphere.", "koordinat": { "enlem": 41.1017, "boylam": 29.0664 } },
    { "isim": "Anadolu Kavağı", "isim_en": "Anadolu Kavagi", "tur": "Balıkçı Köyü / Kale", "tur_en": "Fishing Village / Fortress", "kisa_tarihce": "Şehrin en kuzeyinde, Karadeniz'e açılan kapıda yer alan huzur noktası.", "kisa_tarihce_en": "Peace point located at the northernmost of the city, at the gateway to the Black Sea.", "koordinat": { "enlem": 41.1731, "boylam": 29.0886 } },
    { "isim": "Yoros Kalesi", "isim_en": "Yoros Castle", "tur": "Kale / Manzara", "tur_en": "Castle / View", "kisa_tarihce": "Doğu Roma döneminden kalma, Boğaz ve Karadeniz'e hakim stratejik kale.", "kisa_tarihce_en": "A strategic castle from the East Roman period dominating the Bosphorus and the Black Sea.", "koordinat": { "enlem": 41.1772, "boylam": 29.0944 } },
    { "isim": "Emirgan Korusu", "isim_en": "Emirgan Grove", "tur": "Park / Lale Festivali", "tur_en": "Park / Tulip Festival", "kisa_tarihce": "Köşkleri ve her yıl düzenlenen lale festivaliyle ünlü dev bahçe.", "kisa_tarihce_en": "A huge garden famous for its mansions and the annual tulip festival.", "koordinat": { "enlem": 41.1075, "boylam": 29.0528 }, "gorsel": "https://www.emirganlisuites.com.tr/images/galeri/Istanbul-Emirgan-Korusu-2-950x580(1).jpg" },
    { "isim": "Validebağ Korusu", "isim_en": "Validebag Grove", "tur": "Doğa / Tarih", "tur_en": "Nature / History", "kisa_tarihce": "Adile Sultan Kasrı'na (Hababam Sınıfı Müzesi) ev sahipliği yapan koru.", "kisa_tarihce_en": "The grove hosting the Adile Sultan Pavilion (Hababam Sınıfı Museum).", "koordinat": { "enlem": 41.0118, "boylam": 29.0415 } },
    { "isim": "Şile Feneri", "isim_en": "Sile Lighthouse", "tur": "Deniz Feneri / Manzara", "tur_en": "Lighthouse / View", "kisa_tarihce": "Dünyanın en büyük aktif deniz fenerlerinden biri (1859).", "kisa_tarihce_en": "One of the world's largest active lighthouses (1859).", "koordinat": { "enlem": 41.1778, "boylam": 29.6105 } },
    { "isim": "Yeşilköy Sahili", "isim_en": "Yesilkoy Coast", "tur": "Sahil / Dinlenme", "tur_en": "Coast / Recreation", "kisa_tarihce": "Havacılık Müzesi ve marinasıyla popüler olan, eski adı San Stefano olan semt.", "kisa_tarihce_en": "Popular neighborhood formerly known as San Stefano, with its Aviation Museum and marina.", "koordinat": { "enlem": 40.9575, "boylam": 28.8264 }, "gorsel": "https://www.rotasenin.com/uploads/2025/11/yesilkoy-bakirkoy-sahil-parki-yuruyus-yolu.webp" },
    { "isim": "Büyükada", "isim_en": "Buyukada", "tur": "Ada / Doğa", "tur_en": "Island / Nature", "kisa_tarihce": "Prens Adaları'nın en büyüğü; köşkleri ve Aya Yorgi Kilisesi ile meşhur.", "kisa_tarihce_en": "The largest of the Prince Islands; famous for its mansions and Aya Yorgi Church.", "koordinat": { "enlem": 40.8576, "boylam": 29.1278 } },
    { "isim": "Kanyon AVM", "isim_en": "Kanyon Shopping Mall", "tur": "Alışveriş / Mimari", "tur_en": "Shopping / Architecture", "kisa_tarihce": "Açık hava konseptli ve ödüllü modern kanyon tasarımıyla ünlü alışveriş merkezi.", "kisa_tarihce_en": "A shopping center famous for its open-air concept and award-winning modern canyon design.", "koordinat": { "enlem": 41.0785, "boylam": 29.0114 }, "gorsel": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/4d/84/31/kanyon-alisveris-merkezi.jpg?w=900&h=500&s=1" },
    { "isim": "Aydos Tepesi", "isim_en": "Aydos Hill", "tur": "Doğa / Manzara", "tur_en": "Nature / View", "kisa_tarihce": "İstanbul'un en yüksek noktası ve kalesi bulunan doğal yaşam alanı.", "kisa_tarihce_en": "The highest point in Istanbul and a natural life area with a castle.", "koordinat": { "enlem": 40.9167, "boylam": 29.2501 } },
    { "isim": "Fatih Sultan Mehmet Köprüsü", "isim_en": "Fatih Sultan Mehmet Bridge", "tur": "Köprü", "tur_en": "Bridge", "kisa_tarihce": "Asya ve Avrupa'yı bağlayan ikinci köprü (1988).", "kisa_tarihce_en": "The second bridge connecting Asia and Europe (1988).", "koordinat": { "enlem": 41.0911, "boylam": 29.0608 } },
    { "isim": "Beşiktaş Çarşı", "isim_en": "Besiktas Market", "tur": "Yaşam / Semt", "tur_en": "Life / District", "kisa_tarihce": "Şehrin en dinamik öğrenci ve taraftar kültürünün kalbi.", "kisa_tarihce_en": "The heart of the city's most dynamic student and fan culture.", "koordinat": { "enlem": 41.0428, "boylam": 29.0075 }, "gorsel": "https://blog.obilet.com/wp-content/uploads/2018/05/Be%C5%9Fikta%C5%9F-Kartal-Heykeli.jpg" },
    { "isim": "Emaar Square Istanbul", "isim_en": "Emaar Square Mall", "tur": "Modern Alışveriş / Eğlence", "tur_en": "Modern Shopping / Entertainment", "kisa_tarihce": "Yeraltı akvaryumu ve lüks mağazalarıyla büyük yaşam merkezi.", "kisa_tarihce_en": "A large life center with an underground aquarium and luxury shops.", "koordinat": { "enlem": 41.0021, "boylam": 29.0652 }, "gorsel": "https://akitatours.com/storage/app/uploads/public/0fc/e9d/484/0fce9d484defab151804e727648034e2.jpg" },
    { "isim": "Nevizade Sokağı", "isim_en": "Nevizade Street", "tur": "Eğlence / Gastronomi", "tur_en": "Entertainment / Gastronomy", "kisa_tarihce": "Beyoğlu'nun meşhur meyhaneler sokağı.", "kisa_tarihce_en": "The famous street of taverns in Beyoğlu.", "koordinat": { "enlem": 41.0345, "boylam": 28.9772 } },
    { "isim": "Atatürk Havalimanı Millet Bahçesi", "isim_en": "Ataturk Airport Public Garden", "tur": "Park / Etkinlik", "tur_en": "Park / Event", "kisa_tarihce": "Eski havalimanı arazisine kurulan devasa şehir parkı.", "kisa_tarihce_en": "A massive city park established on the former airport grounds.", "koordinat": { "enlem": 40.9769, "boylam": 28.8144 } },
    { "isim": "Rumeli Kavağı", "isim_en": "Rumeli Kavagi", "tur": "Balıkçı Köyü", "tur_en": "Fishing Village", "kisa_tarihce": "Huzurlu sahil lokantaları ve plajlarıyla bilinen uç semt.", "kisa_tarihce_en": "A remote district known for its peaceful seaside restaurants and beaches.", "koordinat": { "enlem": 41.1811, "boylam": 29.0747 } },
    { "isim": "Büyük Valide Han", "isim_en": "Buyuk Valide Han", "tur": "Tarihi Yapı", "tur_en": "Historical Building", "kisa_tarihce": "Kösem Sultan tarafından yaptırılan, çatısından sunduğu manzarayla ünlü han.", "kisa_tarihce_en": "A guest house built by Kosem Sultan, famous for the view offered from its roof.", "koordinat": { "enlem": 41.0139, "boylam": 28.9691 } },
    { "isim": "Miniatürk", "isim_en": "Miniaturk", "tur": "Açık Hava Müzesi", "tur_en": "Open Air Museum", "kisa_tarihce": "Türkiye ve Osmanlı coğrafyasındaki eserlerin maketlerinden oluşan park.", "kisa_tarihce_en": "A park consisting of models of works in Turkey and the Ottoman geography.", "koordinat": { "enlem": 41.0601, "boylam": 28.9439 } },
    { "isim": "Galataport", "isim_en": "Galataport", "tur": "Alışveriş / Çarşı / Liman", "tur_en": "Shopping / Bazaar / Port", "kisa_tarihce": "Dünyanın ilk yer altı kruvaziyer terminalini barındıran modern sahil bandı.", "kisa_tarihce_en": "Modern coastline containing the world's first underground cruise terminal.", "koordinat": { "enlem": 41.0267, "boylam": 28.9814 }, "gorsel": "https://images.unsplash.com/photo-1590604109724-40660f545195?auto=format&fit=crop&q=80&w=800" },
    { "isim": "Pera Müzesi", "isim_en": "Pera Museum", "tur": "Sanat Müzesi", "tur_en": "Art Museum", "kisa_tarihce": "Tarihi Bristol Oteli binasında bulunan önemli sanat merkezi.", "kisa_tarihce_en": "An important art center located in the historic Bristol Hotel building.", "koordinat": { "enlem": 41.0315, "boylam": 28.9752 }, "gorsel": "https://upload.wikimedia.org/wikipedia/commons/5/5b/Pera_M%C3%BCzesi.jpg" },
    { "isim": "Rahmi M. Koç Müzesi", "isim_en": "Rahmi M. Koc Museum", "tur": "Sanayi Müzesi", "tur_en": "Industrial Museum", "kisa_tarihce": "Sanayi, ulaşım ve iletişim tarihine ışık tutan dev müze.", "kisa_tarihce_en": "A giant museum shedding light on the history of industry, transport and communication.", "koordinat": { "enlem": 41.0422, "boylam": 28.9491 } },
    { "isim": "Sultanahmet Meydanı", "isim_en": "Sultanahmet Square", "tur": "Meydan", "tur_en": "Square", "kisa_tarihce": "Roma'dan bugüne şehrin tören ve etkinlik merkezi olan tarihi meydan.", "kisa_tarihce_en": "Historical square that has been the city's ceremonial and event center since Roman times.", "koordinat": { "enlem": 41.0062, "boylam": 28.9761 } },
    { "isim": "Abbas Ağa Parkı", "isim_en": "Abbasaga Park", "tur": "Park", "tur_en": "Park", "kisa_tarihce": "Beşiktaş'ta sosyal etkinliklerin ve mahalle kültürünün merkezi olan park.", "kisa_tarihce_en": "The park in Beşiktaş which is the center of social events and neighborhood culture.", "koordinat": { "enlem": 41.0461, "boylam": 29.0019 }, "gorsel": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Abbasa%C4%9Fa_Park%C4%B1.jpg/960px-Abbasa%C4%9Fa_Park%C4%B1.jpg" },
    { "isim": "Kariye Camii", "isim_en": "Chora Mosque", "tur": "Cami / Tarihi Yapı", "tur_en": "Mosque / Historical Building", "kisa_tarihce": "Bizans döneminden kalma, mozaik ve freskleriyle ünlü eski bir manastır kilisesidir.", "kisa_tarihce_en": "A former Byzantine monastery church famous for its mosaics and frescoes.", "koordinat": { "enlem": 41.0312, "boylam": 28.9392 } },
    { "isim": "Fatih Camii", "isim_en": "Fatih Mosque", "tur": "Cami", "tur_en": "Mosque", "kisa_tarihce": "Fatih Sultan Mehmed tarafından kentin fethinden sonra yaptırılan ilk büyük sultan camisidir.", "kisa_tarihce_en": "The first major sultan's mosque built by Fatih Sultan Mehmed after the conquest of the city.", "koordinat": { "enlem": 41.0198, "boylam": 28.9497 } },
    { "isim": "Panorama 1453 Tarih Müzesi", "isim_en": "Panorama 1453 History Museum", "tur": "Müze", "tur_en": "Museum", "kisa_tarihce": "İstanbul'un fethini 360 derece panoramik bir resimle anlatan etkileyici müze.", "kisa_tarihce_en": "Impressive museum depicting the conquest of Istanbul with a 360-degree panoramic painting.", "koordinat": { "enlem": 41.0189, "boylam": 28.9204 } },
    { "isim": "Heybeliada", "isim_en": "Heybeliada", "tur": "Ada / Manzara", "tur_en": "Island / View", "kisa_tarihce": "Prens Adaları'nın en yeşil adası, Deniz Lisesi ve Ruhban Okulu ile bilinir.", "kisa_tarihce_en": "The greenest of the Prince Islands, known for the Naval High School and the Halki Seminary.", "koordinat": { "enlem": 40.8775, "boylam": 29.0964 } },
    { "isim": "Burgazada", "isim_en": "Burgazada", "tur": "Ada / Doğa", "tur_en": "Island / Nature", "kisa_tarihce": "Sait Faik Abasıyanık'ın evi ve Kalpazankaya manzarasıyla ünlü huzurlu ada.", "kisa_tarihce_en": "A peaceful island famous for Sait Faik Abasıyanık's house and the Kalpazankaya view.", "koordinat": { "enlem": 40.8814, "boylam": 29.0658 } },
    { "isim": "Kınalıada", "isim_en": "Kinaliada", "tur": "Ada", "tur_en": "Island", "kisa_tarihce": "Şehre en yakın ada, yazlıkçıların ve plajların uğrak noktası.", "kisa_tarihce_en": "The island closest to the city, a frequent spot for summer residents and beaches.", "koordinat": { "enlem": 40.9103, "boylam": 29.0494 } },
    { "isim": "Masumiyet Müzesi (müze)", "isim_en": "The Museum of Innocence (museum)", "tur": "Müze", "tur_en": "Museum", "kisa_tarihce": "Orhan Pamuk'un aynı adlı romanından yola çıkarak kurduğu, Çukurcuma'daki butik müze.", "kisa_tarihce_en": "A boutique museum in Çukurcuma founded by Orhan Pamuk based on his novel of the same name.", "koordinat": { "enlem": 41.0309, "boylam": 28.9796 }, "gorsel": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/The_Museum_of_Innocence.jpg/960px-The_Museum_of_Innocence.jpg" },
    { "isim": "Galata Mevlevihanesi", "isim_en": "Galata Mevlevi House Museum", "tur": "Kültür / Müze", "tur_en": "Culture / Museum", "kisa_tarihce": "İstanbul'un en eski Mevlevihanesi, sema gösterilerinin yapıldığı tarihi mekan.", "kisa_tarihce_en": "Istanbul's oldest Mevlevi house, a historic venue where whirling dervish ceremonies are held.", "koordinat": { "enlem": 41.0278, "boylam": 28.9747 } },
    { "isim": "Çinili Köşk", "isim_en": "Tiled Pavilion", "tur": "Tarihi Yapı / Müze", "tur_en": "Historical Building / Museum", "kisa_tarihce": "Fatih Sultan Mehmed tarafından yaptırılan, Selçuklu etkisindeki seramik müzesi.", "kisa_tarihce_en": "A ceramic museum with Seljuk influence, commissioned by Sultan Mehmed the Conqueror.", "koordinat": { "enlem": 41.0119, "boylam": 28.9818 } },
    { "isim": "İslam Bilim ve Teknoloji Tarihi Müzesi", "isim_en": "Museum of the History of Science and Technology in Islam", "tur": "Müze", "tur_en": "Museum", "kisa_tarihce": "Gülhane Parkı içinde, Müslüman bilim insanlarının buluşlarını sergileyen müze.", "kisa_tarihce_en": "A museum in Gülhane Park exhibiting the inventions of Muslim scientists.", "koordinat": { "enlem": 41.0135, "boylam": 28.9816 } },
    { "isim": "Sakıp Sabancı Müzesi", "isim_en": "Sakip Sabanci Museum", "tur": "Müze / Sanat", "tur_en": "Museum / Art", "kisa_tarihce": "Emirgan'daki Atlı Köşk'te bulunan, hat ve resim koleksiyonuyla ünlü müze.", "kisa_tarihce_en": "A museum famous for its calligraphy and painting collection, located in the Horse Mansion in Emirgan.", "koordinat": { "enlem": 41.1065, "boylam": 29.0565 } },
    { "isim": "İstanbul Modern", "isim_en": "Istanbul Modern", "tur": "Sanat Müzesi", "tur_en": "Art Museum", "kisa_tarihce": "Türkiye'nin ilk modern ve çağdaş sanat müzesi, Karaköy sahilindeki yeni binasındadır.", "kisa_tarihce_en": "Turkey's first modern and contemporary art museum, now in its new building on the Karakoy coast.", "koordinat": { "enlem": 41.0264, "boylam": 28.9825 } },
    { "isim": "Santralİstanbul", "isim_en": "SantralIstanbul", "tur": "Müze / Kültür", "tur_en": "Museum / Culture", "kisa_tarihce": "Eski Silahtarağa Elektrik Santrali'nin dönüştürülmesiyle kurulan enerji ve sanat kompleksi.", "kisa_tarihce_en": "Energy and art complex established by converting the former Silahtarağa Power Plant.", "koordinat": { "enlem": 41.0669, "boylam": 28.9461 } },
    { "isim": "Harbiye Askeri Müze", "isim_en": "Harbiye Military Museum", "tur": "Müze / Tarih", "tur_en": "Museum / History", "kisa_tarihce": "Mehteran gösterileriyle ünlü, dünyanın sayılı askeri müzelerinden biridir.", "kisa_tarihce_en": "One of the world's leading military museums, famous for its Janissary Band performances.", "koordinat": { "enlem": 41.0475, "boylam": 28.9886 } },
    { "isim": "Çamlıca Camii", "isim_en": "Camlica Mosque", "tur": "Cami", "tur_en": "Mosque", "kisa_tarihce": "Cumhuriyet tarihinin en büyük camisi, Çamlıca Tepesi'nde şehre hakim noktadadır.", "kisa_tarihce_en": "The largest mosque in the history of the Republic, located at a point dominating the city on Çamlıca Hill.", "koordinat": { "enlem": 41.0345, "boylam": 29.0708 }, "gorsel": "https://images.ntv.com.tr/images/20840282-987d-4964-965e-008a13bc6c66.jpg?w=1200&height=1200&mode=crop" },
    { "isim": "Eyüp Sultan Camii", "isim_en": "Eyup Sultan Mosque", "tur": "Cami / Türbe", "tur_en": "Mosque / Tomb", "kisa_tarihce": "Ebu Eyyub el-Ensari'nin türbesinin bulunduğu, İslam dünyasının kutsal duraklarından biri.", "kisa_tarihce_en": "One of the holy stops of the Islamic world, where the tomb of Abu Ayyub al-Ansari is located.", "koordinat": { "enlem": 41.0474, "boylam": 28.9339 } },
    { "isim": "Sepetçiler Kasrı", "isim_en": "Sepetciler Pavilion", "tur": "Tarihi Yapı", "tur_en": "Historical Building", "kisa_tarihce": "Sarayburnu sahilinde, Bizans surları üzerine inşa edilmiş bir Osmanlı yapısı.", "kisa_tarihce_en": "An Ottoman building built on the Byzantine walls on the Sarayburnu coast.", "koordinat": { "enlem": 41.0169, "boylam": 28.9839 } },
    { "isim": "Aynalıkavak Kasrı", "isim_en": "Aynalikavak Pavilion", "tur": "Kasır", "tur_en": "Pavilion", "kisa_tarihce": "Haliç kıyısında yer alan, musiki müzesi olarak da kullanılan tarihi köşk.", "kisa_tarihce_en": "A historic pavilion on the Golden Horn coast, also used as a music museum.", "koordinat": { "enlem": 41.0371, "boylam": 28.9554 } },
    { "isim": "Florya Atatürk Deniz Köşkü", "isim_en": "Florya Ataturk Marine Mansion", "tur": "Müze / Kasır", "tur_en": "Museum / Mansion", "kisa_tarihce": "Atatürk'ün dinlenmesi için denizin içine inşa edilmiş modern mimari örneği köşk.", "kisa_tarihce_en": "A modern architectural mansion built into the sea for Atatürk's rest.", "koordinat": { "enlem": 40.9631, "boylam": 28.7997 } },
    { "isim": "Şerefiye Sarnıcı", "isim_en": "Theodosius Cistern", "tur": "Sarnıç / Müze", "tur_en": "Cistern / Museum", "kisa_tarihce": "1600 yıllık tarihiyle, modern restorasyonu ve ışık gösterileriyle ünlü sarnıç.", "kisa_tarihce_en": "A 1600-year-old cistern famous for its modern restoration and light shows.", "koordinat": { "enlem": 41.0076, "boylam": 28.9725 } },
    { "isim": "Binbirdirek Sarnıcı", "isim_en": "Binbirdirek Cistern", "tur": "Sarnıç", "tur_en": "Cistern", "kisa_tarihce": "İstanbul'un ikinci büyük sarnıcı, Bizans dönemi su depolama yapısı.", "kisa_tarihce_en": "The second largest cistern in Istanbul, a Byzantine-era water storage structure.", "koordinat": { "enlem": 41.0081, "boylam": 28.9744 } },
    { "isim": "Cağaloğlu Hamamı", "isim_en": "Cagaloglu Hamami", "tur": "Tarih / Müze / Tarihi Hamam", "tur_en": "History / Museum / Historical Bath", "kisa_tarihce": "1741'de I. Mahmud tarafından yaptırılan, dünyanın en ünlü tarihi hamamlarından.", "kisa_tarihce_en": "Built by Mahmud I in 1741, it is one of the most famous historical baths in the world.", "koordinat": { "enlem": 41.0108, "boylam": 28.9754 } },
    { "isim": "Çemberlitaş Hamamı", "isim_en": "Cemberlitas Hamami", "tur": "Tarih / Müze / Tarihi Hamam", "tur_en": "History / Museum / Historical Bath", "kisa_tarihce": "Mimar Sinan tarafından 1584 yılında III. Murad'ın annesi için inşa edilmiştir.", "kisa_tarihce_en": "Built by Mimar Sinan in 1584 for the mother of Murad III.", "koordinat": { "enlem": 41.0082, "boylam": 28.9715 } },
    { "isim": "Yeni Cami (Eminönü)", "isim_en": "New Mosque", "tur": "Cami", "tur_en": "Mosque", "kisa_tarihce": "Eminönü meydanında yer alan, yapımı 66 yıl süren görkemli Osmanlı camisi.", "kisa_tarihce_en": "A majestic Ottoman mosque in Eminönü square, whose construction took 66 years.", "koordinat": { "enlem": 41.0169, "boylam": 28.9719 }, "gorsel": "https://upload.wikimedia.org/wikipedia/commons/1/13/New_Mosque_in_2025_%2854504109092%29_%28cropped%29.jpg" },
    { "isim": "Malta Köşkü", "isim_en": "Malta Pavilion", "tur": "Tarihi Yapı", "tur_en": "Historical Building", "kisa_tarihce": "Yıldız Parkı içinde yer alan, Sultan Abdülaziz döneminden kalma av köşkü.", "kisa_tarihce_en": "A hunting lodge from the reign of Sultan Abdulaziz, located in Yildiz Park.", "koordinat": { "enlem": 41.0501, "boylam": 29.0135 } },
    { "isim": "Yedikule Zindanları", "isim_en": "Yedikule Dungeons", "tur": "Müze / Tarih", "tur_en": "Museum / History", "kisa_tarihce": "Bizans'ın Altın Kapısı ve Osmanlı'nın zindan olarak kullandığı tarihi kale.", "kisa_tarihce_en": "A historic fortress used as the Golden Gate of Byzantium and a dungeon by the Ottomans.", "koordinat": { "enlem": 40.9937, "boylam": 28.9228 } },
    { "isim": "Hıdiv Kasrı", "isim_en": "Khedive Palace", "tur": "Kasır / Park", "tur_en": "Palace / Park", "kisa_tarihce": "Beykoz'da Mısır Hıdivi Abbas Hilmi Paşa tarafından yaptırılan Art Nouveau köşk.", "kisa_tarihce_en": "Art Nouveau palace built by Abbas Hilmi Pasha, the Khedive of Egypt, in Beykoz.", "koordinat": { "enlem": 41.1058, "boylam": 29.0722 }, "gorsel": "https://www.rotamhikaye.com/wp-content/uploads/2020/06/hidiv-kasri-gezilecek-yerler-16.jpg" },
    { "isim": "Yuşa Tepesi", "isim_en": "Joshua's Hill", "tur": "İnanç / Manzara", "tur_en": "Faith / View", "kisa_tarihce": "Hz. Yuşa'nın makamının bulunduğuna inanılan, Boğaz girişine hakim tepe.", "kisa_tarihce_en": "A hill dominating the entrance to the Bosphorus, believed to be the burial site of Joshua.", "koordinat": { "enlem": 41.1648, "boylam": 29.0915 }, "gorsel": "https://beykozgundemcom.teimg.com/crop/1280x720/beykozgundem-com/images/haberler/2020/11/beykozun-en-huzurlu-yeri-yusa-tepesi_f5010.jpg" },
    { "isim": "Garipçe Köyü", "isim_en": "Garipce Village", "tur": "Doğa / Köy", "tur_en": "Nature / Village", "kisa_tarihce": "Boğaz'ın Karadeniz çıkışında, sakin balıkçı lokantalarıyla ünlü sahil köyü.", "kisa_tarihce_en": "A seaside village famous for its peaceful fish restaurants at the Black Sea exit of the Bosphorus.", "koordinat": { "enlem": 41.2117, "boylam": 29.1089 } },
    { "isim": "Atatürk Kent Ormanı", "isim_en": "Ataturk City Forest", "tur": "Doğa / Park", "tur_en": "Nature / Park", "kisa_tarihce": "Sarıyer'de göletleri ve yürüyüş yollarıyla kentin içindeki devasa yeşil alan.", "kisa_tarihce_en": "A massive green area in the city with its lakes and walking paths in Sarıyer.", "koordinat": { "enlem": 41.1275, "boylam": 29.0255 }, "gorsel": "https://yesil.istanbul/i.php?id=2079&t=herodesktop" }
  ],
  "populer_oteller": [
    { "isim": "Four Seasons Sultanahmet", "isim_en": "Four Seasons Sultanahmet", "kisa_tarihce": "Sultanahmet'te eski bir cezaevinden dönüştürülmüş lüks otel.", "kisa_tarihce_en": "Luxury hotel converted from an old prison in Sultanahmet.", "koordinat": { "enlem": 41.0081, "boylam": 28.9791 }, "gorsel": "https://images.unsplash.com/photo-1566371534003-685cc1c59cfc?auto=format&fit=crop&q=80&w=800" },
    { "isim": "The Ritz-Carlton Istanbul", "isim_en": "The Ritz-Carlton Istanbul", "kisa_tarihce": "Boğaz manzaralı, modern ve lüks konaklama merkezi.", "kisa_tarihce_en": "Modern and luxury accommodation with a Bosphorus view.", "koordinat": { "enlem": 41.0396, "boylam": 28.9928 } },
    { "isim": "Pera Palace Hotel", "isim_en": "Pera Palace Hotel", "kisa_tarihce": "Atatürk, Agatha Christie gibi isimleri ağırlamış tarihi otel.", "kisa_tarihce_en": "Historical hotel that hosted names like Ataturk and Agatha Christie.", "koordinat": { "enlem": 41.0312, "boylam": 28.9739 }, "gorsel": "https://images.unsplash.com/photo-1614742617631-098520894567?auto=format&fit=crop&q=80&w=800" },
    { "isim": "Ciragan Palace Kempinski", "isim_en": "Ciragan Palace Kempinski", "kisa_tarihce": "Eski bir Osmanlı sarayında yer alan eşsiz Boğaz oteli.", "kisa_tarihce_en": "Unique Bosphorus hotel located in a former Ottoman palace.", "koordinat": { "enlem": 41.0441, "boylam": 29.0162 }, "gorsel": "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&q=80&w=800" },
    { "isim": "Swissotel The Bosphorus", "isim_en": "Swissotel The Bosphorus", "kisa_tarihce": "Maçka Parkı'nın yanında, panoramik şehir manzaralı lüks otel.", "kisa_tarihce_en": "Luxury hotel next to Macka Park with a panoramic city view.", "koordinat": { "enlem": 41.0401, "boylam": 28.9987 } },
    { "isim": "The Marmara Taksim", "isim_en": "The Marmara Taksim", "kisa_tarihce": "Taksim Meydanı'nın simgesi olan merkezi ve lüks otel.", "kisa_tarihce_en": "Central and luxury hotel that is the symbol of Taksim Square.", "koordinat": { "enlem": 41.0361, "boylam": 28.9855 } },
    { "isim": "Hilton Istanbul Bosphorus", "isim_en": "Hilton Istanbul Bosphorus", "kisa_tarihce": "Türkiye'nin ilk modern oteli olarak bilinen ikonik yapı.", "kisa_tarihce_en": "Iconic building known as Turkey's first modern hotel.", "koordinat": { "enlem": 41.0449, "boylam": 28.9897 } },
    { "isim": "Shangri-La Bosphorus", "isim_en": "Shangri-La Bosphorus", "kisa_tarihce": "Beşiktaş sahilinde lüks ve konforun buluşma noktası.", "kisa_tarihce_en": "The meeting point of luxury and comfort on the Besiktas coast.", "koordinat": { "enlem": 41.0416, "boylam": 29.0068 } },
    { "isim": "InterContinental Istanbul", "isim_en": "InterContinental Istanbul", "kisa_tarihce": "Taksim bölgesinde şehre hakim konumuyla bilinen prestijli otel.", "kisa_tarihce_en": "Prestigious hotel known for its dominant location over the city in the Taksim area.", "koordinat": { "enlem": 41.0388, "boylam": 28.9876 } },
    { "isim": "Raffles Istanbul", "isim_en": "Raffles Istanbul", "kisa_tarihce": "Zorlu Center kompleksinde yer alan ultra lüks konaklama.", "kisa_tarihce_en": "Ultra-luxury accommodation located in the Zorlu Center complex.", "koordinat": { "enlem": 41.0664, "boylam": 29.0163 } },
    { "isim": "CVK Park Bosphorus", "isim_en": "CVK Park Bosphorus", "kisa_tarihce": "Eski Park Otel arazisinde yükselen modern ve görkemli tesis.", "kisa_tarihce_en": "A modern and majestic facility rising on the site of the former Park Hotel.", "koordinat": { "enlem": 41.0368, "boylam": 28.9881 } },
    { "isim": "Conrad Istanbul Bosphorus", "isim_en": "Conrad Istanbul Bosphorus", "kisa_tarihce": "S eğrisindeki mimarisiyle ünlü Boğaz manzaralı lüks otel.", "kisa_tarihce_en": "Luxury hotel with a Bosphorus view, famous for its S-curved architecture.", "koordinat": { "enlem": 41.0485, "boylam": 29.0090 } },
    { "isim": "Grand Hyatt Istanbul", "isim_en": "Grand Hyatt Istanbul", "kisa_tarihce": "Şehir merkezinde modern tasarımıyla öne çıkan şık otel.", "kisa_tarihce_en": "Stylish hotel standing out with its modern design in the city center.", "koordinat": { "enlem": 41.0405, "boylam": 28.9892 } },
    { "isim": "Sheraton Istanbul City Center", "isim_en": "Sheraton Istanbul City Center", "kisa_tarihce": "Beyoğlu'nun kalbinde modern ve konforlu konaklama.", "kisa_tarihce_en": "Modern and comfortable accommodation in the heart of Beyoğlu.", "koordinat": { "enlem": 41.0385, "boylam": 28.9698 } },
    { "isim": "Divan Istanbul", "isim_en": "Divan Istanbul", "kisa_tarihce": "Türk misafirperverliğini modern lüksle birleştiren köklü otel.", "kisa_tarihce_en": "Well-established hotel combining Turkish hospitality with modern luxury.", "koordinat": { "enlem": 41.0418, "boylam": 28.9877 } },
    { "isim": "Elite World Istanbul", "isim_en": "Elite World Istanbul", "kisa_tarihce": "Taksim bölgesinde klasik ve modern çizgilerin buluştuğu otel.", "kisa_tarihce_en": "Hotel where classic and modern lines meet in the Taksim area.", "koordinat": { "enlem": 41.0382, "boylam": 28.9852 } },
    { "isim": "Titanic Downtown Beyoglu", "isim_en": "Titanic Downtown Beyoglu", "kisa_tarihce": "Beyoğlu bölgesinde modern mimarisiyle konforlu bir seçenek.", "kisa_tarihce_en": "A comfortable option with its modern architecture in the Beyoğlu region.", "koordinat": { "enlem": 41.0365, "boylam": 28.9654 } },
    { "isim": "Soho House Istanbul", "isim_en": "Soho House Istanbul", "kisa_tarihce": "Eski Amerikan Konsolosluğu binasında yer alan özel üyelik kulübü ve otel.", "kisa_tarihce_en": "Private members club and hotel located in the former American Consulate building.", "koordinat": { "enlem": 41.0298, "boylam": 28.9721 } },
    { "isim": "Wyndham Grand Istanbul Levant", "isim_en": "Wyndham Grand Istanbul Levant", "kisa_tarihce": "Levent finans merkezinde yer alan modern iş ve yaşam oteli.", "kisa_tarihce_en": "Modern business and lifestyle hotel located in the Levent financial center.", "koordinat": { "enlem": 41.0765, "boylam": 29.0123 } },
    { "isim": "Point Hotel Barbaros", "isim_en": "Point Hotel Barbaros", "kisa_tarihce": "Sanat ve teknolojiyi birleştiren modern konseptli otel.", "kisa_tarihce_en": "Modern concept hotel combining art and technology.", "koordinat": { "enlem": 41.0621, "boylam": 29.0065 } },
    { "isim": "Renaissance Istanbul Polat Bosphorus", "isim_en": "Renaissance Istanbul Polat Bosphorus", "kisa_tarihce": "Beşiktaş sırtlarında harika şehir ve Boğaz manzaralı otel.", "kisa_tarihce_en": "Hotel with great city and Bosphorus views on the slopes of Besiktas.", "koordinat": { "enlem": 41.0585, "boylam": 29.0042 } },
    { "isim": "Dedeman Istanbul", "isim_en": "Dedeman Istanbul", "kisa_tarihce": "Geleneksel Türk misafirperverliğini odağına alan köklü tesis.", "kisa_tarihce_en": "Well-established facility focusing on traditional Turkish hospitality.", "koordinat": { "enlem": 41.0652, "boylam": 29.0012 } },
    { "isim": "The Stay Bosphorus", "isim_en": "The Stay Bosphorus", "kisa_tarihce": "Ortaköy'de denize sıfır, butik ve şık konaklama deneyimi.", "kisa_tarihce_en": "Waterfront, boutique and stylish accommodation experience in Ortakoy.", "koordinat": { "enlem": 41.0478, "boylam": 29.0272 } },
    { "isim": "A'jia Hotel", "isim_en": "A'jia Hotel", "kisa_tarihce": "Kanlıca sahilinde, tarihi bir yalıda butik konaklama keyfi.", "kisa_tarihce_en": "Boutique accommodation pleasure in a historic mansion on the Kanlica coast.", "koordinat": { "enlem": 41.1042, "boylam": 29.0654 } },
    { "isim": "Sumahan on the Water", "isim_en": "Sumahan on the Water", "kisa_tarihce": "Çengelköy'de eski bir damıtım evinden dönüştürülmüş butik otel.", "kisa_tarihce_en": "Boutique hotel converted from an old distillery in Cengelköy.", "koordinat": { "enlem": 41.0545, "boylam": 29.0521 } },
    { "isim": "Bebek Hotel by The Stay", "isim_en": "Bebek Hotel by The Stay", "kisa_tarihce": "Bebek sahilinin en ikonik ve köklü butik otellerinden biri.", "kisa_tarihce_en": "One of the most iconic and established boutique hotels on the Bebek coast.", "koordinat": { "enlem": 41.0772, "boylam": 29.0435 } },
    { "isim": "Mandarin Oriental Bosphorus", "isim_en": "Mandarin Oriental Bosphorus", "kisa_tarihce": "Kuruçeşme sahilinde lüksün en üst seviyesini sunan modern otel.", "kisa_tarihce_en": "Modern hotel offering the highest level of luxury on the Kurucesme coast.", "koordinat": { "enlem": 41.0612, "boylam": 29.0345 } },
    { "isim": "Six Senses Kocatas Mansions", "isim_en": "Six Senses Kocatas Mansions", "kisa_tarihce": "Sarıyer sahilinde tarihi iki köşkte yer alan lüks ve wellness odaklı otel.", "kisa_tarihce_en": "Luxury and wellness-oriented hotel located in two historic mansions on the Sariyer coast.", "koordinat": { "enlem": 41.1652, "boylam": 29.0512 } },
    { "isim": "Fuad Pasa Yalisi", "isim_en": "Fuad Pasa Yalisi", "kisa_tarihce": "19. yüzyıldan kalma tarihi bir paşa yalısında eşsiz konaklama.", "kisa_tarihce_en": "Unique accommodation in a historic 19th-century pasha's mansion.", "koordinat": { "enlem": 41.1212, "boylam": 29.0712 } },
    { "isim": "Grand Tarabya", "isim_en": "Grand Tarabya", "kisa_tarihce": "Tarabya koyuna hakim, İstanbul'un en köklü otellerinden biri.", "kisa_tarihce_en": "One of Istanbul's most established hotels, dominating the Tarabya bay.", "koordinat": { "enlem": 41.1412, "boylam": 29.0552 } },
    { "isim": "Hilton Istanbul Bakirkoy", "isim_en": "Hilton Istanbul Bakirkoy", "kisa_tarihce": "Marmara Denizi kıyısında modern ve konforlu sahil oteli.", "kisa_tarihce_en": "Modern and comfortable seaside hotel on the shores of the Marmara Sea.", "koordinat": { "enlem": 40.9752, "boylam": 28.8512 } },
    { "isim": "Sheraton Istanbul Atakoy", "isim_en": "Sheraton Istanbul Atakoy", "kisa_tarihce": "Ataköy Marina'da yer alan huzurlu sahil oteli.", "kisa_tarihce_en": "Peaceful seaside hotel located in Ataköy Marina.", "koordinat": { "enlem": 40.9712, "boylam": 28.8752 } },
    { "isim": "Hyatt Regency Istanbul Atakoy", "isim_en": "Hyatt Regency Istanbul Atakoy", "kisa_tarihce": "Modern tasarımıyla Ataköy sahilinde lüks segment konaklama.", "kisa_tarihce_en": "Luxury segment accommodation on the Ataköy coast with modern design.", "koordinat": { "enlem": 40.9721, "boylam": 28.8652 } },
    { "isim": "DoubleTree by Hilton Moda", "isim_en": "DoubleTree by Hilton Moda", "kisa_tarihce": "Kadıköy Moda'da, panoramik Adalar ve Boğaz manzaralı modern otel.", "kisa_tarihce_en": "Modern hotel in Kadıköy Moda with panoramic Prince Islands and Bosphorus views.", "koordinat": { "enlem": 40.9852, "boylam": 29.0252 } },
    { "isim": "Wyndham Grand Kalamis", "isim_en": "Wyndham Grand Kalamis", "kisa_tarihce": "Kalamış Marina'nın kalbinde yer alan prestijli sahil oteli.", "kisa_tarihce_en": "Prestigious seaside hotel located in the heart of Kalamış Marina.", "koordinat": { "enlem": 40.9782, "boylam": 29.0382 } },
    { "isim": "Park Hyatt Istanbul Macka Palas", "isim_en": "Park Hyatt Istanbul Macka Palas", "kisa_tarihce": "Nişantaşı'nın en şık binalarından Maçka Palas'ta lüks konaklama.", "kisa_tarihce_en": "Luxury accommodation in Maçka Palas, one of Nişantaşı's most stylish buildings.", "koordinat": { "enlem": 41.0482, "boylam": 28.9952 } },
    { "isim": "W Istanbul", "isim_en": "W Istanbul", "kisa_tarihce": "Akaretler Sıraevler'de yer alan şık ve dinamik butik otel.", "kisa_tarihce_en": "Stylish and dynamic boutique hotel located in Akaretler Row Houses.", "koordinat": { "enlem": 41.0423, "boylam": 29.0005 } },
    { "isim": "Ajwa Sultanahmet", "isim_en": "Ajwa Sultanahmet", "kisa_tarihce": "Sultanahmet'te Osmanlı saray mimarisini modern lüksle buluşturan otel.", "kisa_tarihce_en": "Hotel in Sultanahmet bringing Ottoman palace architecture together with modern luxury.", "koordinat": { "enlem": 41.0058, "boylam": 28.9712 } },
    { "isim": "Legacy Ottoman Hotel", "isim_en": "Legacy Ottoman Hotel", "kisa_tarihce": "Eminönü sahilinde, tarihi 4. Vakıf Han binasında yer alan görkemli otel.", "kisa_tarihce_en": "Majestic hotel located in the historic 4th Vakıf Han building on the Eminönü coast.", "koordinat": { "enlem": 41.0162, "boylam": 28.9742 } }


  ]
};

export const TRANSLATIONS = {
  tr: {
    title: "İstanbul Akıllı Rehber", discover: "İstanbul'u Keşfet", subtitle: "Sizin için en mantıklı gezi rotasını hazırlıyoruz.",
    start: "Hemen Başla", planner: "Seyahat Planlayıcı", hotelStart: "Otelden Başla", districtStart: "Semtten Başla",
    hotelLabel: "Konakladığınız Otel", districtLabel: "Başlangıç Semti", duration: "Süre", days: "GÜN",
    interests: "İlgi Alanları", dailyPace: "Günlük Tempo", dailyPaceTooltip: "Bu seçenekle, bir gün içerisinde toplam kaç farklı yeri ziyaret etmek istediğinizi belirleyebilirsiniz.", paceScale: ["Yavaş", "Normal", "Yoğun", "Zirve"],
    createRoute: "Rota Çiz", calculating: "Hesaplanıyor...", dailyRoute: "Günlük Rota Planınız", day: "GÜN",
    directions: "Yol Tarifi",
    audioGuide: "Sesli Rehber", howItWorks: "Nasıl Çalışır?", about: "Hakkımızda", goToMap: "Haritaya Git",
    settings: "Ayarları Aç", serverActive: "Sunucu Aktif", dataStandards: "Kültür ve Turizm Bakanlığı Veri Standartları",
    howItWorksTitle: "Akıllı Rota Teknolojisi", ready: "Keşfetmeye Hazırım", aboutTitle: "Hakkımızda",
    howItWorksDesc: "Otelini veya gezmek istediğin semti seç, gün sayısını belirle; yapay zekamız senin için en kısa ulaşım süreli ve en mantıklı gezi rotasını anında hazırlasın!",
    optimization: "Mesafe Optimizasyonu", optimizationDesc: "En yakın noktalar algoritma ile sıralanır.",
    typeFiltering: "Tür Bazlı Filtreleme", typeFilteringDesc: "Sadece ilgi duyduğunuz kategoriler dâhil edilir.",
    aboutDesc: "İstanbul Akıllı Rehber, dünyanın en güzel şehirlerinden biri olan İstanbul'u en verimli şekilde gezebilmeniz için geliştirilmiş yapay zeka destekli bir rotalama platformudur.",
    cats: {
      worship: "İbadet & İnanç",
      history: "Tarih & Müze",
      nature: "Doğa & Park",
      views: "Seyir & Manzara",
      shopping: "Alışveriş & Çarşı",
      water: "Sahil & Ada",
      transport: "Mimari & Ulaşım",
      fortress: "Kale & Hisar",
      life: "Meydan & Yaşam",
      fun: "Eğlence & Sanat"
    },
    districts: {
      "Adalar": "Adalar", "Arnavutköy": "Arnavutköy", "Ataşehir": "Ataşehir", "Avcılar": "Avcılar", "Bağcılar": "Bağcılar",
      "Bahçelievler": "Bahçelievler", "Bakırköy": "Bakırköy", "Başakşehir": "Başakşehir", "Bayrampaşa": "Bayrampaşa",
      "Beşiktaş": "Beşiktaş", "Beykoz": "Beykoz", "Beylikdüzü": "Beylikdüzü", "Beyoğlu": "Beyoğlu", "Büyükçekmece": "Büyükçekmece",
      "Çatalca": "Çatalca", "Çekmeköy": "Çekmeköy", "Esenler": "Esenler", "Esenyurt": "Esenyurt", "Eyüpsultan": "Eyüpsultan",
      "Fatih": "Fatih", "Gaziosmanpaşa": "Gaziosmanpaşa", "Gungören": "Güngören", "Kadıköy": "Kadıköy", "Kağıthane": "Kağıthane",
      "Kartal": "Kartal", "Küçükçekmece": "Küçükçekmece", "Maltepe": "Maltepe", "Pendik": "Pendik", "Sancaktepe": "Sancaktepe",
      "Sarıyer": "Sarıyer", "Silivri": "Silivri", "Sultanbeyli": "Sultanbeyli", "Sultangazi": "Sultangazi", "Şile": "Şile",
      "Şişli": "Şişli", "Tuzla": "Tuzla", "Ümraniye": "Ümraniye", "Üsküdar": "Üsküdar", "Zeytinburnu": "Zeytinburnu"
    }
  },
  en: {
    title: "Istanbul Smart Guide", discover: "Discover Istanbul", subtitle: "We prepare the most logical travel route for you.",
    start: "Start Now", planner: "Travel Planner", hotelStart: "Start from Hotel", districtStart: "Start from District",
    hotelLabel: "Your Hotel", districtLabel: "Starting District", duration: "Duration", days: "DAYS",
    interests: "Interests", dailyPace: "Daily Pace", dailyPaceTooltip: "With this option, you can determine how many different places you want to visit in total in one day.", paceScale: ["Relaxed", "Normal", "Active", "Peak"],
    createRoute: "Create Route", calculating: "Calculating...", dailyRoute: "Your Daily Route Plan", day: "DAY",
    directions: "Directions",
    audioGuide: "Audio Guide", howItWorks: "How it Works?", about: "About Us", goToMap: "Go to Map",
    settings: "Open Settings", serverActive: "Server Active", dataStandards: "Ministry of Culture and Tourism Data Standards",
    howItWorksTitle: "Smart Route Technology", ready: "I'm Ready to Explore", aboutTitle: "About Us",
    howItWorksDesc: "Choose your hotel or the district you want to visit, set the number of days; our AI will instantly prepare the most logical travel route with the shortest transportation time for you!",
    optimization: "Distance Optimization", optimizationDesc: "Nearest points are ordered by algorithm.",
    typeFiltering: "Type-Based Filtering", typeFilteringDesc: "Only categories you are interested in are included.",
    aboutDesc: "Istanbul Smart Guide is an AI-powered routing platform developed to help you visit Istanbul, one of the most beautiful cities in the world, in the most efficient way.",
    cats: {
      worship: "Worship & Faith",
      history: "History & Museum",
      nature: "Nature & Park",
      views: "Views & Scenery",
      shopping: "Shopping & Bazaar",
      water: "Coast & Island",
      transport: "Architecture & Transport",
      fortress: "Fortress & Defense",
      life: "Square & Life",
      fun: "Entertainment & Art"
    },
    districts: {
      "Adalar": "Princes' Islands", "Arnavutköy": "Arnavutkoy", "Ataşehir": "Atasehir", "Avcılar": "Avcilar", "Bağcılar": "Bagcilar",
      "Bahçelievler": "Bahcelievler", "Bakırköy": "Bakirkoy", "Başakşehir": "Basaksehir", "Bayrampaşa": "Bayrampasa",
      "Beşiktaş": "Besiktas", "Beykoz": "Beykoz", "Beylikdüzü": "Beylikduzu", "Beyoğlu": "Beyoglu", "Büyükçekmece": "Buyukcekmece",
      "Çatalca": "Catalca", "Çekmeköy": "Cekmekoy", "Esenler": "Esenler", "Esenyurt": "Esenyurt", "Eyüpsultan": "Eyupsultan",
      "Fatih": "Fatih", "Gaziosmanpaşa": "Gaziosmanpasa", "Gungören": "Gungoren", "Kadıköy": "Kadikoy", "Kağıthane": "Kagithane",
      "Kartal": "Kartal", "Küçükçekmece": "Kucukcekmece", "Maltepe": "Maltepe", "Pendik": "Pendik", "Sancaktepe": "Sancaktepe",
      "Sarıyer": "Sariyer", "Silivri": "Silivri", "Sultanbeyli": "Sultanbeyli", "Sultangazi": "Sultangazi", "Şile": "Sile",
      "Şişli": "Sisli", "Tuzla": "Tuzla", "Ümraniye": "Umraniye", "Üsküdar": "Uskudar", "Zeytinburnu": "Zeytinburnu"
    }
  }
};

export const ALL_DISTRICTS = ["Adalar", "Arnavutköy", "Ataşehir", "Avcılar", "Bağcılar", "Bahçelievler", "Bakırköy", "Başakşehir", "Bayrampaşa", "Beşiktaş", "Beykoz", "Beylikdüzü", "Beyoğlu", "Büyükçekmece", "Çatalca", "Çekmeköy", "Esenler", "Esenyurt", "Eyüpsultan", "Fatih", "Gaziosmanpaşa", "Gungören", "Kadıköy", "Kağıthane", "Kartal", "Küçükçekmece", "Maltepe", "Pendik", "Sancaktepe", "Sarıyer", "Silivri", "Sultanbeyli", "Sultangazi", "Şile", "Şişli", "Tuzla", "Ümraniye", "Üsküdar", "Zeytinburnu"];

export const DISTRICT_COORDS: { [key: string]: { lat: number, lng: number } } = {
  "Adalar": { lat: 40.8715, lng: 29.1311 }, "Arnavutköy": { lat: 41.1852, lng: 28.7417 }, "Ataşehir": { lat: 40.9924, lng: 29.1272 }, "Avcılar": { lat: 41.0003, lng: 28.7184 },
  "Bağcılar": { lat: 41.0341, lng: 28.8354 }, "Bahçelievler": { lat: 41.0051, lng: 28.8622 }, "Bakırköy": { lat: 40.9829, lng: 28.8617 }, "Başakşehir": { lat: 41.0805, lng: 28.8016 },
  "Bayrampaşa": { lat: 41.045, lng: 28.8996 }, "Beşiktaş": { lat: 41.0428, lng: 29.0075 }, "Beykoz": { lat: 41.1352, lng: 29.1023 }, "Beylikdüzü": { lat: 41.0012, lng: 28.6417 },
  "Beyoğlu": { lat: 41.0369, lng: 28.9851 }, "Büyükçekmece": { lat: 41.0189, lng: 28.5917 }, "Çatalca": { lat: 41.1444, lng: 28.4611 }, "Çekmeköy": { lat: 41.0352, lng: 29.1722 },
  "Esenler": { lat: 41.0392, lng: 28.8856 }, "Esenyurt": { lat: 41.0267, lng: 28.6784 }, "Eyüpsultan": { lat: 41.0474, lng: 28.9339 }, "Fatih": { lat: 41.015, lng: 28.94 },
  "Gaziosmanpaşa": { lat: 41.0652, lng: 28.9117 }, "Gungören": { lat: 41.0252, lng: 28.8717 }, "Kadıköy": { lat: 40.9904, lng: 29.0305 }, "Kağıthane": { lat: 41.0825, lng: 28.9754 },
  "Kartal": { lat: 40.8891, lng: 29.1852 }, "Küçükçekmece": { lat: 41.0019, lng: 28.7754 }, "Maltepe": { lat: 40.9452, lng: 29.1352 }, "Pendik": { lat: 40.8769, lng: 29.2319 },
  "Sancaktepe": { lat: 41.0052, lng: 29.2317 }, "Sarıyer": { lat: 41.1714, lng: 29.0569 }, "Silivri": { lat: 41.0741, lng: 28.2475 }, "Sultanbeyli": { lat: 40.9652, lng: 29.2617 },
  "Sultangazi": { lat: 41.1052, lng: 28.8717 }, "Şile": { lat: 41.1752, lng: 29.6117 }, "Şişli": { lat: 41.0602, lng: 28.9876 }, "Tuzla": { lat: 40.8152, lng: 29.3017 },
  "Ümraniye": { lat: 41.0252, lng: 29.0917 }, "Üsküdar": { lat: 41.0267, lng: 29.0156 }, "Zeytinburnu": { lat: 40.9884, lng: 28.8951 }
};

export type Venue = typeof ISTANBUL_DATA.turistik_mekanlar[0];
export type Hotel = typeof ISTANBUL_DATA.populer_oteller[0];
